[package]
name = "fib_max_rs"
version = "0.1.0"
authors = ["Iv Maskim <maivkin@gmail.com>"]
edition = "2021"

[lib]
name = "fib_max_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }



